### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by 708yamaguchi** [708yamaguchi/pr2_fingertip_sensors#1]
- Change project name (g491_makabe -> ???)
- Add firmware for sensors

**Comment by makabe0510** [comment]
プロジェクト名変更 -> .iocや.projectとかの中のプロジェクト名の文字列を手動で書き換える

**Comment by 708yamaguchi** [comment]
*IMUをI2Cで読んでみる
*暫定で送るフォーマットを決める
*PR2と繋いで試す

**Comment by makabe0510** [comment]
金沢君Todo
・Altium Designerのライセンス発行を先生に頼む
・インストールして、チュートリアルを終わらせる

**Comment by 708yamaguchi** [comment]
> PR2と繋いで試す

ADC、I2C（近接、IMU）、I2S（マイク）を全部読むプログラムはできた。
確かこのコミット：https://github.com/708yamaguchi/pr2_fingertip_sensors/commit/cf0397167bd7113abed8acfd08210ac6ac868af5

ここに、PR2と通信するためのSPIスレーブ機能を加えると上手くいかない。
具体的には、PR2のrostopicから得られる値が安定しない or 何かのセンサが読めていない

試したら良いこと
- FreeRTOSでセンサごとにタスクを作るのではなく、全てメインループに入れてみる（シングルコアなので、あるタスクが別タスク中に実行されてしまうと、通信が失敗することがある）
- メインループにかかる時間を測定する。PR2がセンサデータを読む周期が40msなので、これ以内に収まるかが大事
- メインループは時間がかかりすぎる場合は、`if (i==0); readADC(); else if (i==1) readIMU() ... else sendSPI()`のように、各ループごとに行う処理を分ける
- I2Sだけはタイミングがシビアなので、タイマー割り込みにしても良いかも知れない。

**Comment by 708yamaguchi** [comment]
FreeRTOSバージョンとシングルスレッドバージョンを簡単に切り替えられるようにする。
できれば、code generationのみ or #define のみで切り替えられるようにする。

**Comment by 708yamaguchi** [comment]
各センサとの通信をDMAにすると上手く行きそうなので、山口と真壁で自分が使いたいセンサ通信をDMAにする。

原因として考えられるのは、シングルコアのCPUにタスクを振りすぎて、途中で中断したくないセンサ通信までも中断されていたこと。
DMAにするとCPUリソースを使わないので、この問題が解決するかもしれない。

**Comment by makabe0510** [comment]
ブレイクポイントを打ってICM-42688-PをI2C+DMAで読むのが一応できました
ただ、UARTでの出力と同居できず、検証を進めた所HAL_I2C_Mem_Read_DMAを呼んだ上で途中でICM-42688-Pからの返信が無くなるようでした
しばらく更新がなかった場合にHAL_I2C_Mem_Read_DMAを呼び直しても通信できませんでした

そのため、なるべく通信時間を軽くする方法を検証した所、通信周波数を最大で1MHzまで挙げられて、その運用で読むことができました
基本的に4000[us]、最悪で20000[us]程度になったようです

**Comment by 708yamaguchi** [comment]
おー、仕事が早い
さすがです

> ただ、UARTでの出力と同居できず、

まあ本番はUART使わないし、SPIスレーブと同居できたら問題ないね

> なるべく通信時間を軽くする方法を検証した所、通信周波数を最大で1MHzまで挙げられて

これはI2C通信にかかる時間を短くしたということ？

> 基本的に4000[us]、最悪で20000[us]程度になったようです

これはI2C通信+UART通信にかかる時間の合計？

**Comment by 708yamaguchi** [comment]
了解です
情報共有助かりました。

僕も明日は朝からI2SのDMAやります。

**Comment by 708yamaguchi** [comment]
I2SマイクのDMA通信 + FreeRTOSをしてみました。
コメントで@makabe0510に質問しているので時間があるときに教えてもらいたいです。
https://github.com/708yamaguchi/pr2_fingertip_sensors/pull/18


あと以下のコメントにあるIMU+DMAのプログラムを、一応プルリクエストにしておいてください。
https://github.com/708yamaguchi/pr2_fingertip_sensors/issues/1#issuecomment-1154057979

**Comment by 708yamaguchi** [comment]
以下のプルリクエストをもって、マイク以外は安定バージョンになった気がします。
https://github.com/708yamaguchi/pr2_fingertip_sensors/pull/27

@makabe0510 
https://github.com/708yamaguchi/pr2_fingertip_sensors/pull/27#issuecomment-1156707926 のコメントにあるように、マイクを安定させるためには他のセンサがマイコンリソースを奪いすぎないことが重要だと自分は考えているので、他のセンサもDMA化したいです。
一方で設計を進めることが最優先だと思うので、発注してから基板が届くまでの間のタスクにするのが良いかなと考えています。
