### ISSUE TITLE
Nucleo G491REでI2S+SPIを3系統全部を使う方法

### ISSUE THREAD

**Issue by 708yamaguchi** [708yamaguchi/pr2_fingertip_sensors#24]
STM32 G491REには、SPIが合計3系統存在する。
そのうちSPI2とSPI3は、I2Sとして利用することも出来る。
https://github.com/708yamaguchi/pr2_fingertip_sensors/blob/master/Datasheets/stm32g491re.pdf

しかしNucleo G491REではSPI1が使えず、SPI1として利用できるピンは他の機能に利用されている。
CubeIDEでNucleo G491REプロジェクトのPinoutを設定するときに表示されるエラーは以下。
```
SPI1:
Serial Peripheral Interface
Status:
Not available:
PA5 mapped with GPIO_Output or/and
PB3 mapped with SYS_JTDO-SWO
```

そこで、CubeIDEでSTM32 G491RE（注：Nucleo G491REではない）用のプロジェクトを作る。
この場合、PA5やPA3に上記の機能を割り当てる必要がなく、SPI1の機能を割り当てることが出来る。
ただし、SYS_JTDO-SWO機能を割り当てていないため、デバッグは行えなくなる。（要検証）

このとき、USB経由ではNucleoに書き込み出来ない（要検証）
しかし、PCにUSB接続したST-LINKとNucleoの間で以下のようにピンを接続することで、書き込みを行える。
このとき、5V_SELのジャンパピンを、5V_STLKからE5Vにすることを忘れない。
- E5V （5Vの給電、Nucleoにはシルクで書かれている）
- GND
- T_SWDIO（初期設定ではPA13）
- T_SWCLK（初期設定ではPA14）

**Comment by 708yamaguchi** [comment]
> そこで、CubeIDEでSTM32 G491RE（注：Nucleo G491REではない）用のプロジェクトを作る。

Nucleo G491REのプロジェクトを作って、PinoutでSYS_JTDO-SWOをSPI1用に割り当てればよい。

> SYS_JTDO-SWO機能を割り当てていないため、デバッグは行えなくなる。
> USB経由ではNucleoに書き込み出来ない

さっき試した感じだと、おそらく両方USB経由で出来る

**Comment by makabe0510** [comment]
今まで4線で試した感じブレイクポイントを打つデバッグはできてました

**Comment by makabe0510** [comment]
SWOがあるとprintfデバッグができる感じっぽいです
https://yukblog.net/stm32cubeide-printf-swo/

**Comment by 708yamaguchi** [comment]
> 今まで4線で試した感じブレイクポイントを打つデバッグはできてました

これUSBでも出来てしまいました。。。

> SWOがあるとprintfデバッグができる感じっぽいです
[yukblog.net/stm32cubeide-printf-swo](https://yukblog.net/stm32cubeide-printf-swo/)

なるほど
SWOはUARTとは関係ないから、SWOピンをdisableしてもUART経由でシリアルモニタに文字を送れるってことね
勉強になります
